import Header from '@/components/Layout/Header/Header'
import './globals.css'
// import { Inter } from 'next/font/google'

import localFont from 'next/font/local'

import Footer from '@/components/Layout/Footer/Footer'

// const inter = Inter({ subsets: ['latin'] })

const FontAwesome = localFont({
  src: [
    {
      path: 'fonts/fontawesome-webfont.woff2',
      weight: 'normal',
      style: 'normal',
    },
  
  ],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={FontAwesome.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
